
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkdvibtyvnsinygkqxds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrZHZpYnR5dm5zaW55Z2txeGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MzE0NTUsImV4cCI6MjA1NDEwNzQ1NX0.drqPskpmSuA9FOT6IHjM3hzTBJpiuT6oHli9x9gzgRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Long syncs fire hundreds of requests; a dropped connection surfaces as
// "TypeError: Failed to fetch". Retry those network-level failures a few times
// with backoff before giving up. (HTTP error responses are never retried.)
const fetchWithRetry: typeof fetch = async (input, init) => {
  const delays = [400, 1200, 3000];
  for (let attempt = 0; ; attempt++) {
    try {
      return await fetch(input, init);
    } catch (err) {
      if (attempt >= delays.length || init?.signal?.aborted) throw err;
      await new Promise((r) => setTimeout(r, delays[attempt]));
    }
  }
};

// The scheduled sync (Node) may supply a service-role key so it keeps working
// now that database writes are admin-only. Never set in the browser.
const nodeEnv = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
const SUPABASE_KEY = nodeEnv?.SUPABASE_SERVICE_ROLE_KEY || SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  global: { fetch: fetchWithRetry },
});
