
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkdvibtyvnsinygkqxds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrZHZpYnR5dm5zaW55Z2txeGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MzE0NTUsImV4cCI6MjA1NDEwNzQ1NX0.drqPskpmSuA9FOT6IHjM3hzTBJpiuT6oHli9x9gzgRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
